export { default as HomePage } from "./HomePage"
export { default as RegisterPage } from "./RegisterPage"
export { default as PageNotFound } from "./PageNotFound"
export { default as MainPage } from "./MainPage"
export { default as SettingsPage } from "./SettingsPage"